//types used to get artist listing according to the genres types selected
export const GET_ARTIST_LISTING_GENRESTYPE ='GET_ARTIST_LISTING_GENRESTYPE';
export const GET_ARTIST_LISTING_GENRESTYPE_SUCCESS ='GET_ARTIST_LISTING_GENRESTYPE_SUCCESS'
export const GET_ARTIST_LISTING_GENRESTYPE_FAILED ='GET_ARTIST_LISTING_GENRESTYPE_FAILED'